INSERT INTO %db_prefix%modules (module_name,module_display_name,module_description,module_status,module_version,activation_hook) VALUES ('lab', 'Lab',"Suggest and Charge for lab tests. Upload and View Reports", '1','0.0.1','activate');
CREATE TABLE %db_prefix%tests( test_id int(11) NOT NULL AUTO_INCREMENT, test_name varchar(25) NOT NULL, test_charges int(10) NOT NULL,PRIMARY KEY (test_id));
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('lab_test', 'administration', 800,'lab/tests', 'fa-user-md', 'lab_tests','lab');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('lab_tests', '', 500,'lab/view_lab_tests', 'fa-flask', 'lab_reports','lab');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('pending_lab_tests', 'lab_tests', 100,'lab/view_lab_tests/pending', NULL, 'pending','lab');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('complete_lab_tests', 'lab_tests', 200,'lab/view_lab_tests/complete', NULL, 'complete','lab');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'lab_test', 'System Administrator', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'lab_tests', 'System Administrator', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'pending_lab_tests', 'System Administrator', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'lab_tests', 'Lab Technician', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'pending_lab_tests', 'Lab Technician', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'complete_lab_tests', 'System Administrator', '1');
INSERT INTO %db_prefix%menu_access ( menu_name, category_name, allow) VALUES ( 'complete_lab_tests', 'Doctor', '1');
INSERT INTO %db_prefix%user_categories (category_name) VALUES ( 'Lab Technician');
CREATE TABLE %db_prefix%visit_lab_r ( visit_test_id int(11) NOT NULL AUTO_INCREMENT, visit_id int(11) NOT NULL, test_id int(11) NOT NULL, is_deleted int(11) DEFAULT NULL, sync_status int(11) DEFAULT NULL,  PRIMARY KEY (visit_test_id));
ALTER TABLE %db_prefix%visit_lab_r ADD UNIQUE KEY visit_lab_r_uq (visit_id,test_id);
ALTER TABLE %db_prefix%visit_lab_r ADD status VARCHAR(12) NOT NULL DEFAULT 'pending' AFTER sync_status;
ALTER TABLE %db_prefix%visit_lab_r ADD file_name VARCHAR(50) NULL AFTER status;
ALTER TABLE %db_prefix%visit_lab_r ADD report_date DATE NULL AFTER file_name;
CREATE OR REPLACE VIEW %db_prefix%view_lab_tests AS SELECT patient.patient_name,       patient.patient_id,       visit_lab_r.status,	   tests.test_name,	   visit_lab_r.visit_test_id,	   visit_lab_r.visit_id,	   visit_lab_r.report_date,	   visit.visit_date,	   visit.visit_time,	   visit_lab_r.file_name FROM %db_prefix%visit_lab_r AS visit_lab_r JOIN %db_prefix%visit AS visit ON visit.visit_id =  visit_lab_r.visit_id JOIN %db_prefix%view_patient AS patient ON visit.patient_id = patient.patient_id JOIN %db_prefix%tests AS tests ON tests.test_id = visit_lab_r.test_id;
UPDATE %db_prefix%modules SET module_version = '0.0.2' WHERE module_name = 'lab';
ALTER TABLE %db_prefix%visit_lab_r CHANGE visit_id visit_id INT(11) NULL;
ALTER TABLE %db_prefix%visit_lab_r ADD bill_id INT(11) NULL AFTER visit_id;
CREATE OR REPLACE VIEW %db_prefix%view_lab_tests AS SELECT patient.patient_name,       patient.patient_id,       visit_lab_r.status,	   tests.test_name,	   visit_lab_r.visit_test_id,	   visit_lab_r.visit_id,	   visit_lab_r.bill_id,	   visit_lab_r.report_date,	   visit.visit_date AS date,	   visit.visit_time AS time,	    visit_lab_r.file_name  FROM %db_prefix%visit_lab_r AS visit_lab_r JOIN %db_prefix%visit AS visit ON visit.visit_id =  visit_lab_r.visit_id JOIN %db_prefix%view_patient AS patient ON visit.patient_id = patient.patient_id JOIN %db_prefix%tests AS tests ON tests.test_id = visit_lab_r.test_id UNION SELECT patient.patient_name,    patient.patient_id,       visit_lab_r.status,	   tests.test_name,	   visit_lab_r.visit_test_id,	   visit_lab_r.visit_id,visit_lab_r.bill_id,	   visit_lab_r.report_date,	   bill.bill_date as date,	   bill.bill_time as time,	    visit_lab_r.file_name  FROM %db_prefix%visit_lab_r AS visit_lab_r JOIN %db_prefix%bill AS bill ON bill.bill_id =  visit_lab_r.bill_id JOIN %db_prefix%view_patient AS patient ON bill.patient_id = patient.patient_id JOIN %db_prefix%tests AS tests ON tests.test_id = visit_lab_r.test_id;
UPDATE %db_prefix%modules SET module_version = '0.0.3' WHERE module_name = 'lab';
